version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: employee-docs-postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - employee_network

  api:
    build: .
    container_name: employee-docs-api
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      # Outras variáveis necessárias como JWT_SECRET etc.
    ports:
      - "3000:3000"
    networks:
      - employee_network
    command: npm run start:prod # ou apenas: node dist/main

volumes:
  postgres_data:

networks:
  employee_network:
